### ISSUE TITLE
aladhan api request limit

### ISSUE THREAD

**Issue by sahilmushtaq** [islamic-network/aladhan-api-client-php#3]
Hi,

i was testing aladhan api. i faced  below message. I want to confirm is there api request limit?

{
    "code": 429,
    "status": "Too Many Requests",
    "data": "You have been rate limited temporarily. Please contact the Site Administrator for more information."
}

Thanks

**Comment by meezaan** [comment]
Al Salaamu Alaykum,

Yes, it's 250 requests every 30 seconds. Are you using IPv4 or IPv6?

**Comment by sahilmushtaq** [comment]
Salaamu Alaykum,

Thanks for reply. It's IPv4.

Thanks

**Comment by meezaan** [comment]
OK, IPv6 is slightly different because of the Docker Swarm's limitations, but that is the range, more or less.

**Comment by mylab4492** [comment]
Hi, 
I am getting same error even when I'm sending 1request per minute
